### ISSUE TITLE
Conda environment creation failing

### ISSUE THREAD

**Issue by stephenjboyle** [probs-lab/probs-ontology#3]
@ricklupton 
Creating a Conda environment for prodcom-data using file:
 https://github.com/probs-lab/prodcom-data/blob/rcl-rdfox-modules-6.3/environment.yml
results in error:
WARNING: Generating metadata for package probs-ontology produced metadata for project name probs-module-ontology. Fix your #egg=probs-ontology fragments.
Discarding git+https://github.com/probs-lab/probs-ontology.git@6384788d8ba83810713d8253400ef0f0280a9d4f#egg=probs-ontology: Requested probs-module-ontology from git+https://github.com/probs-lab/probs-ontology.git@6384788d8ba83810713d8253400ef0f0280a9d4f#egg=probs-ontology has inconsistent name: expected 'probs-ontology', but metadata has 'probs-module-ontology'

I think changing line ```name = "probs-module-ontology"``` to ```name = "probs-ontology"``` in file
https://github.com/probs-lab/probs-ontology/blob/v2/pyproject.toml
will fix this. 
Is it ok to make this change?

**Comment by ricklupton** [comment]
@stephenjboyle I was thinking it should be the other way round -- keep it called `probs-module-ontology` for consistency with the other `probs-module-*`, and change `egg=probs-ontology` to `egg=probs-module-ontology`?

**Comment by stephenjboyle** [comment]
@ricklupton 
Thanks Rick, that works ok now. I've updated the environment file for rcl-rdfox-modules-6.3
